### ISSUE TITLE
can't diagonal bridge if there is no nearby block and 2 block hole

### ISSUE THREAD

**Issue by RoriFoha** [Avanatiker/client#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by theredstoner** [comment]
It would be helpful if you could attach a screenshot of the situation you are describing

**Comment by natan515** [comment]
Yes you should give more details cus rn there is no way for the dev to fix it, if they don't know what rly is that bug and what cause it.

**Comment by EnigmA-008** [comment]
I tested this behavior in single player with a manually created cave. 

**Screenshot**
![grafik](https://user-images.githubusercontent.com/76707270/103243756-18b07080-495b-11eb-837d-1f0f3fbd7771.png)

**Behavior**
The bot is not able to bridge over the cave and changes back and forth between obsidian and netherrack in the hotbar.

**Comment by RoriFoha** [comment]
sorry for late reply and this is not what I meant, i meant that when you
put the mode on tunnel and there is a big hole infront of the tunnel it
can't diagonally bridge ( if the hole was big or a neather cave) so I have
to come and make a diagonal bridge so I can continue digging while afk.

**Comment by RoriFoha** [comment]
If there is a supporting block (beside it) it would build but if there was
nothing so it can't build anything. as you see in the pic.

‫في الاثنين، 28 ديسمبر 2020 في 4:30 م تمت كتابة ما يلي بواسطة ‪Rasheed
Gamer‬‏ <‪rasheedshamma204@gmail.com‬‏>:‬

> sorry for late reply and this is not what I meant, i meant that when you
> put the mode on tunnel and there is a big hole infront of the tunnel it
> can't diagonally bridge ( if the hole was big or a neather cave) so I have
> to come and make a diagonal bridge so I can continue digging while afk.
>

**Comment by RoriFoha** [comment]
![2020-12-28_16 33 33](https://user-images.githubusercontent.com/76264841/103244421-f1da4600-492a-11eb-8ec0-0d7b96e9629c.png)
![2020-12-28_16 32 53](https://user-images.githubusercontent.com/76264841/103244422-f272dc80-492a-11eb-964e-8951b50b9946.png)
![2020-12-28_16 33 26](https://user-images.githubusercontent.com/76264841/103244423-f30b7300-492a-11eb-9dc2-e4c6b0a435d8.png)

**Comment by natan515** [comment]
L
> **Behavior**
> The bot is not able to bridge over the cave and changes back and forth between obsidian and netherrack in the hotbar. 
> 
> 

Super weird cus for me it's ok, check ur settings and version

**Comment by natan515** [comment]
Its a known bug the bot can't place blocks if they aren't connected to anything.

**Comment by RoriFoha** [comment]
is there anyway that bot builds the entire 3x3 tunnel like the one shown in
the salc1 video (the longest road in minecraft)

**Comment by natan515** [comment]
Please rename it to, can't place blocks that aren't connected to anything. @RoriFoha

**Comment by zincodrone** [comment]
This is an issue with baritone itself. Bridging is very buggy with standalone Baritone and I believe this could be due to a safeguard.

**Comment by RoriFoha** [comment]
is there any way that this could be fixed?

**Comment by Natan515** [comment]
Yes but its hard
