### ISSUE TITLE
Changing the filler block to obsidian leads to bot getting stuck

### ISSUE THREAD

**Issue by EnigmA-008** [Avanatiker/client#23]
**Describe the bug**
The schematic for straight and diagonal highways does not work if the filler block is set to obsidian.

**To Reproduce**
Set up the highway mode as usual (i.e. 4 high and 6 wide, without corner block) and execute the command ;ht filler obsidian. Start HT and see the bot get stuck. It tries to mine the corner block that is covered by the existing highway. Just tested in single player.

**Expected behavior**
The HT should work as they normally do but use obsidian instead of netherrack to fill lava pockets.

**Additional context / media**
Diagonal highway
![grafik](https://user-images.githubusercontent.com/76707270/103242787-d3d70a80-4957-11eb-94b8-4ff0e1c2b0a0.png)
Straight Highway
![grafik](https://user-images.githubusercontent.com/76707270/103242815-e7827100-4957-11eb-8d58-7d1a865cb555.png)

**Comment by natan515** [comment]
I'm pretty sure the pull req is fixing it.

**Comment by EnigmA-008** [comment]
I encounter the same bug in v06 (on straight and diagonal highways).
