### ISSUE TITLE
AutoObsidian tool handling: Use Silktouch pick for digging, use Fortune pick for echests

### ISSUE THREAD

**Issue by EnigmA-008** [Avanatiker/client#28]
**Purpose:** if players are low on picks and want to use them as efficient as possible it is necessary to use fortune picks for echests and all other picks (i.e. silktouch or unenchanted diamond) for digging. This is a problem if the tunnel is not pre-dug since this uses lots of durability of the precious fortune pick.

**Describe the solution you'd like**
Setting for proper use of picks. if turned on, autoobsidian prefers fortune picks and digging netherrack prefers  the best picks first (first enchanted, then unenchanted diamond). Also, ItemSaver in InventoryManager can be turned on so that the last fortune pick will not be used and can be mended (with xp bottles or by using mining quartz).

**Comment by theredstoner** [comment]
AutoObsidian change here: https://github.com/Avanatiker/client/pull/31
