### ISSUE TITLE
AutoObsidian dont mines echest occasionally

### ISSUE THREAD

**Issue by EnigmA-008** [Avanatiker/client#36]
**Describe the bug**
During the AutoObsidian process it happens that it does not mines the echest that has been placed. Occasionally it does not even places the chest. The bug happens in v07 and did not happen in v05. changing the settings does not help.

**To Reproduce**
Start AutoObsidian and wait for the bug. 

**Expected behavior**
All chests that have been placed during AutoObsidian shall be mined.

**Debug info**
Probably buggy due to the rewrite of the AutoObsidian module. 

**Additional context / media**
Bot is stuck:
![grafik](https://user-images.githubusercontent.com/76707270/103487982-759fa100-4e09-11eb-9e72-bb80b8806100.png)

Settings:
![grafik](https://user-images.githubusercontent.com/76707270/103487989-8ea85200-4e09-11eb-9447-b2cdb49c2f93.png)

**Comment by theredstoner** [comment]
Can you please try setting delayTicks to 3 and let me know if this still happens?

**Comment by theredstoner** [comment]
Was able to reproduce this with tickDelay 2
