### ISSUE TITLE
[AutoObsidian] Moving Shulkers from inventory to hotbar not working on 2b2t

### ISSUE THREAD

**Issue by theredstoner** [Avanatiker/client#39]
It might be sending packets too quickly. Maybe needs a delay before moving and placing.

**Comment by theredstoner** [comment]
Adding a delay causes additional problems. It turns out its 2b2t's anticheat is causing this issue.

**Comment by huddy987** [comment]
Fixed here: https://github.com/kami-blue/client/commit/c471c4867932172de5c1f042775002c642b2a8e6
