### ISSUE TITLE
[HighwayTools] Activate AntiAFK after the player ran out of resources

### ISSUE THREAD

**Issue by EnigmA-008** [Avanatiker/client#47]
**Is your feature request related to a problem? Please describe.**
Yes. It the module stops (because it is out of resources) and the player is afk he will be kicked due to being afk. 

**Describe the solution you'd like**
Toggleable option (according to ToggleAutoObsidian) to activate AntiAFK after the module stopped working. And since there is a ping sound if it is out of obsidian HT could be tried to be activated every 30 seconds to get the ping sound again (to wake up the person or to go on working if the first stop was by mistake).

**Comment by Avanatiker** [comment]
Added
