### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Potterfanz** [Avanatiker/client#56]
**Describe the bug**
Stuck while PLACE for more  -> then <- 20 ticks, refreshing data.

**Expected behavior**
Please replace then with than at some point

![2021-03-29_00 40 00](https://user-images.githubusercontent.com/34488308/112791754-2d6ed400-9030-11eb-9aef-a848e471c7c8.png)

**Comment by Avanatiker** [comment]
Thanks for the suggestion :) if all fixes would be that easy :D
